version: '2'
services:
  alesia-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/Alesia/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Alesia
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5433
